# Generated by Django 3.0.7 on 2020-06-18 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=200, verbose_name='网站名称')),
                ('site_description', models.TextField(default='', max_length=1000, verbose_name='网站描述')),
                ('per_page_count', models.IntegerField(default=10, verbose_name='文章列表每页数目')),
                ('article_sub_length', models.IntegerField(default=300, verbose_name='文章摘要长度')),
                ('sidebar_article_count', models.IntegerField(default=5, verbose_name='侧边栏文章数目')),
                ('sidebar_comment_count', models.IntegerField(default=5, verbose_name='侧边栏评论数目')),
                ('open_site_comment', models.BooleanField(default=True, verbose_name='是否打开网站评论功能')),
                ('theme', models.PositiveIntegerField(choices=[(1, '默认主题'), (2, '其他主题')], default=1, verbose_name='模板主题')),
                ('record_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='网站备案号')),
                ('is_enable', models.BooleanField(default=False, verbose_name='是否启用')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '网站配置',
                'verbose_name_plural': '网站配置',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='链接名称')),
                ('href', models.URLField(verbose_name='链接')),
                ('is_enable', models.BooleanField(default=True, verbose_name='是否展示')),
                ('weight', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1, help_text='权重高展示顺序靠前', verbose_name='权重')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '友链',
                'verbose_name_plural': '友链',
                'ordering': ['-weight'],
            },
        ),
        migrations.CreateModel(
            name='SideBar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('type', models.PositiveIntegerField(choices=[(1, 'HTML'), (2, '标签统计'), (3, '最新文章'), (4, '最热文章'), (5, '最近评论'), (6, '友情链接')], default=1, verbose_name='展示类型')),
                ('content', models.CharField(blank=True, help_text='如果设置的不是HTML类型，可为空', max_length=1000, verbose_name='内容')),
                ('is_enable', models.BooleanField(default=True, verbose_name='是否展示')),
                ('order', models.IntegerField(unique=True, verbose_name='排序')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '侧边栏',
                'verbose_name_plural': '侧边栏',
                'ordering': ['order'],
            },
        ),
    ]
