# Generated by Django 3.0.7 on 2020-07-07 09:34

import apps.config.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_auto_20200618_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogsettings',
            name='background_image',
            field=models.ImageField(default='background_image/default.jpg', upload_to=apps.config.models.background_image_path, verbose_name='用户头像'),
        ),
        migrations.AlterField(
            model_name='sidebar',
            name='content',
            field=models.TextField(blank=True, help_text='如果设置的不是HTML类型，可为空', verbose_name='内容'),
        ),
    ]
