# Generated by Django 3.0.7 on 2020-07-09 02:03

import apps.config.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_auto_20200707_1734'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='blogsettings',
        #     name='created_time',
        #     field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
        #     preserve_default=False,
        # ),
        migrations.AlterField(
            model_name='blogsettings',
            name='article_sub_length',
            field=models.IntegerField(default=200, verbose_name='文章摘要长度'),
        ),
        migrations.AlterField(
            model_name='blogsettings',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.config.models.background_image_path, verbose_name='背景图片'),
        ),
    ]
