# Generated by Django 3.0.7 on 2020-07-07 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200624_2106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sort'], 'verbose_name': '分类', 'verbose_name_plural': '分类'},
        ),
    ]
