# Generated by Django 3.0.7 on 2020-07-09 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200707_1734'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-on_top', '-pub_time'], 'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
    ]
